#!/usr/bin/env bash

# install ansible
sudo apt update
sudo apt install software-properties-common -y
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install -y ansible git

# execute playbook
ansible-pull -K -U https://github.com/Squirrelz/ansible.git -t ubuntu local.yml

