#!/usr/bin/env bash

printf "\033[35mUpdating APT and installing Ansible\033[0m\n"
sudo apt update
sudo apt install software-properties-common -y
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install -y ansible git

if [[ -d ~/.ansible/pull/$HOSTNAME]]; then
	printf "\033[0;35mCleaning up script\033[0m\n"
	rm -rf ~/.ansible/pull/$HOSTNAME
fi

printf "\033[35mpulling ansible dir\033[0m\n"
git clone https://github.com/Squirrelz/ansible.git ~/.ansible/pull/$HOSTNAME

echo "\033[35mRunning ansible playbook\033[0m"
ansible-playbook -K --ask-vault-password -t ubuntu ansible/local.yml


