#!/usr/bin/env bash

sudo apt update
sudo apt install software-properties-common -y
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install -y ansible git

git clone https://github.com/Squirrelz/ansible.git ~/.squirrelzansible

ansible-playbook -K --ask-vault-password ~/.squirrelzansible/local.yml

rm -rf ~/.squirrelzansible

