- hosts: localhost
  connection: local
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    the_user: "{{ ansible_user_id }}"
  tasks:
  - import_tasks: tasks/ssh.yml
  - import_tasks: tasks/core-packages.yml
  - import_tasks: tasks/golang.yml
  - import_tasks: tasks/tmux.yml
  - import_tasks: tasks/tmux-plugins.yml
  - import_tasks: tasks/fzf.yml
  - import_tasks: tasks/lf.yml
  - import_tasks: tasks/pistol.yml
  - import_tasks: tasks/neovim.yml
  - import_tasks: tasks/network.yml
  - import_tasks: tasks/zsh.yml
  - import_tasks: tasks/omnisharp-lsp.yml
  - import_tasks: tasks/docker.yml
  - import_tasks: tasks/dotfiles.yml
  - import_tasks: tasks/neovim-post.yml
