- hosts: localhost
  connection: local
  vars_files:
    - "vars/common.yml"

  tasks:
  - import_tasks: tasks/ssh.yml
    tags: tmux, always

  - include_tasks: "os/{{ ansible_os_family | lower }}-core.yml"
    tags: always

  - include_tasks: "os/{{ ansible_os_family | lower }}-optional.yml"

  - import_tasks: tasks/lf.yml

  - import_tasks: tasks/neovim.yml
    tags: nvim

  - import_tasks: tasks/zsh.yml
    tags: always

  - import_tasks: tasks/lsp-omnisharp.yml
    
  - import_tasks: tasks/dotfiles.yml
    tags: always

  - import_tasks: tasks/neovim-post.yml
    tags: nvim, never
