#!/usr/bin/env bash

declare -A osInfo;
osInfo[/etc/redhat-release]=dnf
osInfo[/etc/arch-release]=pacman
osInfo[/etc/gentoo-release]=emerge
osInfo[/etc/SuSE-release]=zypp
osInfo[/etc/debian_version]=apt-get
osInfo[/etc/alpine-release]=apk

for f in ${!osInfo[@]}
do
    if [[ -f $f ]];then
	sudo ${osInfo[$f]} install -y ansible git

	git clone https://github.com/Squirrelz/ansible.git ~/.squirrelzansible

	ansible-playbook -K --ask-vault-password -t nvim ~/.squirrelzansible/local.yml

	rm -rf ~/.squirrelzansible
    fi
done

