- name: Install System Packages 1/3
  become: true
  package:
    name:
    - build-essential
    - keychain
    - cmake
    - pkg-config
    - libpthread-stubs0-dev
    state: latest

- name: Install System Packages 2/3
  become: true
  package:
    name:
    - lua5.1
    - unzip
    - libtool
    - libtool-bin
    - gettext
    state: latest

- name: Install System Packages 3/3
  become: true
  package:
    name:
    - compton
    - direnv
    - moreutils
    - htop
    - lsof
    - i3
    - dunst
    - polybar
    - rofi
    - feh
    - cargo
    - keepassxc
    - ccache
    - ninja-build
    - python3-pip
    - dconf-editor
    - nvidia-settings
    - pavucontrol
    - moreutils
    - clangd
    state: latest

- name: Install Clang
  become: true
  package:
    name:
    - clang
    - clangd
    state: present

- name: Ensure .local bin folder exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
