- name: Install System Packages 1/2 (build-essential, keychain, cmake, pkg-config, libpthread-stubs0-dev)
  become: true
  package:
    name:
    - build-essential
    - keychain
    - cmake
    - pkg-config
    - libpthread-stubs0-dev
    state: latest
    tag: always

- name: Install System Packages 2/2 (lua5.1, unzip, libtool, libtool-bin, gettext)
  become: true
  package:
    name:
    - lua5.1
    - unzip
    - libtool
    - libtool-bin
    - gettext
    state: latest
    tag: always

- name: Install luxury packages
  become: true
  package:
    name:
    - compton
    - direnv
    - moreutils
    - htop
    - lsof
    - i3
    - dunst
    - polybar
    - rofi
    - feh
    - cargo
    - keepassxc
    - ccache
    - ninja-build
    - python3-pip
    - dconf-editor
    - nvidia-settings
    - pavucontrol
    - moreutils
    - clang
    - clangd
    state: latest

- name: Ensure .local bin folder exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
