- name: Assign docker path
  stat:
    path: "{{ lookup('env', 'HOME') }}/.docker/cli-plugins"
  register: docker_path

- name: Install Docker dependencies
  become: true
  package:
    name:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    state: present

- name: Install Docker's official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  when: docker_path.stat.exists == False

- name: Setup Docker's stable repository
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: docker_path.stat.exists == False

- name: Install Docker engine
  become: true
  apt:
    update_cache: true
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Remove docker compose directory if it exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.docker/cli-plugins"
    state: absent

- name: Ensure .docker/cli-plugins path exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.docker/cli-plugins"
    state: directory

- name: Register latest docker compose version
  shell: |
    curl --silent "https://api.github.com/repos/docker/compose/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")' | cut -c 2-
  register: compose_ver

- name: Install Docker Compose to the plugins path (1/2)
  shell: curl -SL https://github.com/docker/compose/releases/download/v{{ compose_ver.stdout }}/docker-compose-linux-x86_64 -o {{ lookup('env', 'HOME') }}/.docker/cli-plugins/docker-compose

- name: Install Docker Compose to the plugins path (2/2)
  file:
    path: "{{ lookup('env', 'HOME') }}/.docker/cli-plugins/docker-compose"
    state: file
    mode: a+x