# nvim hex highlighting plugin support, pistol install
- name: Add golang ppa
  become: yes
  apt_repository:
    repo: ppa:longsleep/golang-backports
    state: present

- name: Install golang
  become: yes
  apt:
    name: golang-go