- name: Remove neovim
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/neovim"
    state: absent

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"

- name: Neovim Plugin Development 1
  become: true
  package:
    name: luarocks
    state: present

- name: Neovim Plugin Development 2 luacheck
  become: true
  shell: luarocks install luacheck

- name: Remove Neovim install files
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/neovim"
    state: absent
