- name: Run Neovim headless PlugInstall/PlugUpdate
  command: "nvim --headless -c 'autocmd User PackerSync quitall' -c 'PackerSync'"

- name: TabNine installation
  shell: "cd {{ lookup('env', 'HOME')}}/.local/share/nvim/site/pack/packer/start/cmp-tabnine && ./install.sh"
