- name: Clone N
  ansible.builtin.git:
    repo: 'https://github.com/tj/n.git'
    dest: "{{ lookup('env', 'HOME') }}/n"

- name: Install N
  become: true
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/n"
    target: install

- name: Install correct version of Node
  become: true
  shell: n 14
  tags:
    - install
    - node

- name: npmjs prefix
  shell: mkdir -p {{ lookup('env', 'HOME') }}/.local/.npm-global
  tags:
  - install
  - node

- name: add npmjs to path
  shell: PATH={{ lookup('env', 'HOME') }}/.local/.npm-global/bin:$PATH
  tags:
  - install
  - node

- name: npmjs global settings
  shell: npm config set prefix '{{ lookup('env', 'HOME') }}/.local/.npm-global'
  tags:
  - install
  - node

- name: npmjs global settings export path in case I don't have dotfiles installed
  shell: export PATH={{ lookup('env', 'HOME') }}/.local/.npm-global/bin:$PATH
  tags:
  - install
  - node
  - npm-path

- name: Remove Neovim install files
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/n"
    state: absent
