- name: Remove omnisharp binary dir if it exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/omnisharp"
    state: absent

- name: Ensure omnisharp dir target path exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/omnisharp"
    state: directory
- name: Download omnisharp tarball and unarchive into local folder
  unarchive:
    src: https://github.com/OmniSharp/omnisharp-roslyn/releases/latest/download/omnisharp-linux-x64.tar.gz
    dest: "{{ lookup('env', 'HOME') }}/.local/omnisharp"
    remote_src: yes