- name: Remove tmux if installed
  become: true
  package:
    name: tmux
    state: absent

- name: Install required tmux build packages
  become: true
  package:
    name:
    - libevent-dev
    - ncurses-dev
    - bison
    - pkg-config
    - build-essential
    - checkinstall

- name: Register latest tmux version
  shell: |
    curl --silent "https://api.github.com/repos/tmux/tmux/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")'
  register: tmux_ver
  args:
    warn: false


- name: Create tmux install directory
  become: true
  file:
    path: "{{ lookup('env', 'HOME') }}/.tmux-install"
    state: directory

- name: Download tmux tarball and unarchive into .tmux-install
  become: true
  unarchive:
    src: 'https://github.com/tmux/tmux/releases/latest/download/tmux-{{ tmux_ver.stdout }}.tar.gz'
    dest: "{{ lookup('env', 'HOME') }}/.tmux-install"
    remote_src: yes

- name: Build tmux from tarball
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/.tmux-install/tmux-{{ tmux_ver.stdout }} && ./configure && make"

- name: Install tmux
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/.tmux-install/tmux-{{ tmux_ver.stdout }} && checkinstall -y"

- name: Remove tmux install directory
  become: true
  file:
    path: "{{ lookup('env', 'HOME') }}/.tmux-install"
    state: absent