- name: Install ZSH
  become: true
  apt: name=zsh
  tags:
    - install
    - ubuntu
    - zsh
    
- name: Change shell to zsh
  become: yes
  user:
    name:  "{{ the_user }}}"
    shell: "chsh -s ${which zsh}"
  tags:
    - install
    - ubuntu
    - zsh

- name: Check that the somefile.conf exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_stats
  tags:
    - install
    - ubuntu
    - zsh

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags:
    - install
    - ubuntu
    - zsh
  when: oh_my_stats.stat.exists == False
  become_user: "{{ the_user }}}"

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - install
    - ubuntu
    - zsh

- name: Install zsh-nvm
  ansible.builtin.git:
    repo: 'https://github.com/lukechilds/zsh-nvm.git'
    dest: "~/.oh-my-zsh/plugins/zsh-nvm"
  tags:
    - install
    - ubuntu
    - zsh