- name: Install luxury packages
  become: true
  package:
    name:
    - compton
    - direnv
    - htop
    - lsof
    - i3
    - dunst
    - polybar
    - rofi
    - feh
    - keepassxc
    - ccache
    - ninja-build
    - python3-pip
    - dconf-editor
    - pavucontrol
    - wireshark
    - tshark
    - ngrep
    - python3
    - pip
    - ripgrep
    state: latest

- name: Install pip packages
  ansible.builtin.pip:
    break-system-packages: true
    name: diff-highlight
